### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fkromer** [Project-Menelaos/c-flowchart#2]
The **dot** version of the project does use **pycparser** to parse the c files in _c-flowchart / dot_graph.py / generate_call_tree(filename)_. But what syntax (dot, mermaid) does the following call of _print_mermaid_graph(tree, file)_ generate? How can i run the tests or examples on my local machine? Is there documentation in english available?

**Comment by Jamesits** [comment]
Mermaid refers to: https://github.com/knsv/mermaid
Documentation is missing because I wrote these in 1 day for auto-generating my term paper... Sorry for this. I will fix bugs and fill docs later.

**Comment by fkromer** [comment]
Don't hurry... i was just confused because **mermaid** has a different graph representation syntax as **dot** has.

**Comment by fkromer** [comment]
Don't hurry... i was just confused because **mermaid** has a different graph representation syntax as **dot** has.
