### ISSUE TITLE
Flowgraph support

### ISSUE THREAD

**Issue by fkromer** [Project-Menelaos/c-flowchart#3]
Flowgraphs do summarize statements (e.g. function/method calls) into a node in comparison with flowcharts which represent each statement (process step) as separat node. Do you plan to add support for flowcharts? One could e.g. either (a) "print" the parsed statements of a subpath (~ process block) as strings into a node or (b) print all parsed comment statements within a subpath as string into a node or (c) print only "keyword marked" comments in a subpath as string into a node.

**Comment by Jamesits** [comment]
I think LLVM can generate flowgraphs in graphviz (`dot`) format from LLVM IR and it does better than me.

**Comment by fkromer** [comment]
Thanks a lot for the hint! I did find some [starting point for further reading](http://stackoverflow.com/questions/27310166/automatically-generate-flowcharts-out-of-c-code) about graph generation with **clang/llvm**.
